//
// AdditionalInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Object which is contains brands and categories associated with this suggestion. */
public struct AdditionalInfo: Codable, JSONEncodable, Hashable {

    public var brands: [String]
    public var categories: [String]

    public init(brands: [String], categories: [String]) {
        self.brands = brands
        self.categories = categories
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case brands
        case categories
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(brands, forKey: .brands)
        try container.encode(categories, forKey: .categories)
    }
}

