//
// Audience.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The target group associated with a given audience (e.g. male, veterans, car owners, musicians, etc.) of the product. */
public struct Audience: Codable, JSONEncodable, Hashable {

    /** The genders of the audience. Strongly encouraged to use the standard values: 'male', 'female', 'unisex'. At most 5 values are allowed. Length limit of 128 characters. */
    public var genders: [String]?
    /** The age groups of the audience. Strongly encouraged to use the standard values: 'newborn' (up to 3 months old), 'infant' (3-12 months old), 'toddler' (1-5 years old), 'kids' (5-13 years old), 'adult' (typically teens or older). At most 5 values are allowed. Length limit of 128 characters. */
    public var ageGroups: [String]?

    public init(genders: [String]? = nil, ageGroups: [String]? = nil) {
        self.genders = genders
        self.ageGroups = ageGroups
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case genders
        case ageGroups
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(genders, forKey: .genders)
        try container.encodeIfPresent(ageGroups, forKey: .ageGroups)
    }
}

