//
// BiasDtoStrengthDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The amount the bias will affect the search results. */
public enum BiasDtoStrengthDto: String, Codable, CaseIterable {
    case absoluteIncrease = "ABSOLUTE_INCREASE"
    case strongIncrease = "STRONG_INCREASE"
    case mediumIncrease = "MEDIUM_INCREASE"
    case weakIncrease = "WEAK_INCREASE"
    case leaveUnchanged = "LEAVE_UNCHANGED"
    case weakDecrease = "WEAK_DECREASE"
    case mediumDecrease = "MEDIUM_DECREASE"
    case strongDecrease = "STRONG_DECREASE"
    case absoluteDecrease = "ABSOLUTE_DECREASE"
}
