//
// BiasingProfileDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Inline biasing profile, which should be applied to the search. Takes priority over biasing profile. */
public struct BiasingProfileDto: Codable, JSONEncodable, Hashable {

    public var biases: [BiasDto]

    public init(biases: [BiasDto]) {
        self.biases = biases
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case biases
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(biases, forKey: .biases)
    }
}

