//
// BiasDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Biases the search results to either increase or decrease product relevancy for products that match the given field and content. */
public struct BiasDto: Codable, JSONEncodable, Hashable {

    /** The field the bias refers to. */
    public var field: String
    /** The content the field must match for the bias to be applied. */
    public var content: String?
    public var strength: BiasDtoStrengthDto

    public init(field: String, content: String? = nil, strength: BiasDtoStrengthDto) {
        self.field = field
        self.content = content
        self.strength = strength
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case field
        case content
        case strength
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(field, forKey: .field)
        try container.encodeIfPresent(content, forKey: .content)
        try container.encode(strength, forKey: .strength)
    }
}

