//
// BoostedProductBucket.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BoostedProductBucket: Codable, JSONEncodable, Hashable {

    public var products: [String]

    public init(products: [String]) {
        self.products = products
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case products
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(products, forKey: .products)
    }
}

