//
// CustomParameterDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A key&#x3D;value combination to allow for further triggering of rules or redirects. */
public struct CustomParameterDto: Codable, JSONEncodable, Hashable {

    /** Key of the custom parameter. */
    public var key: String
    /** Value of the custom parameter */
    public var value: String

    public init(key: String, value: String) {
        self.key = key
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case key
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(key, forKey: .key)
        try container.encode(value, forKey: .value)
    }
}

