//
// DebugDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Contains debug info associated to response. */
public struct DebugDto: Codable, JSONEncodable, Hashable {

    /** Search request in raw format executed internally against search engine. */
    public var rawSearchRequest: [AnyCodable]?
    /** Search response in raw format received internally from search engine. */
    public var rawSearchResponse: [AnyCodable]?

    public init(rawSearchRequest: [AnyCodable]? = nil, rawSearchResponse: [AnyCodable]? = nil) {
        self.rawSearchRequest = rawSearchRequest
        self.rawSearchResponse = rawSearchResponse
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case rawSearchRequest
        case rawSearchResponse
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(rawSearchRequest, forKey: .rawSearchRequest)
        try container.encodeIfPresent(rawSearchResponse, forKey: .rawSearchResponse)
    }
}

