//
// ExperimentVariant.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ExperimentVariant: Codable, JSONEncodable, Hashable {

    public var name: String
    public var ruleVariant: RuleVariant
    public var variantTriggerPercentage: Int

    public init(name: String, ruleVariant: RuleVariant, variantTriggerPercentage: Int) {
        self.name = name
        self.ruleVariant = ruleVariant
        self.variantTriggerPercentage = variantTriggerPercentage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case ruleVariant
        case variantTriggerPercentage
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(ruleVariant, forKey: .ruleVariant)
        try container.encode(variantTriggerPercentage, forKey: .variantTriggerPercentage)
    }
}

