//
// FacetSearchRequestDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Request that should be populated to configure a search API call, made by the client on behalf of a shopper. Contains original request and information about facet for which extra keys requested. */
public struct FacetSearchRequestDto: Codable, JSONEncodable, Hashable {

    public var facet: Facet
    public var originalRequest: SearchRequestDto

    public init(facet: Facet, originalRequest: SearchRequestDto) {
        self.facet = facet
        self.originalRequest = originalRequest
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case facet
        case originalRequest
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(facet, forKey: .facet)
        try container.encode(originalRequest, forKey: .originalRequest)
    }
}

