//
// FacetSearchResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Facet search response representation. */
public struct FacetSearchResponseDto: Codable, JSONEncodable, Hashable {

    public var originalRequest: SearchRequestDto
    public var availableNavigation: NavigationDto

    public init(originalRequest: SearchRequestDto, availableNavigation: NavigationDto) {
        self.originalRequest = originalRequest
        self.availableNavigation = availableNavigation
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case originalRequest
        case availableNavigation
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(originalRequest, forKey: .originalRequest)
        try container.encode(availableNavigation, forKey: .availableNavigation)
    }
}

