//
// FilterParameter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FilterParameter: Codable, JSONEncodable, Hashable {

    static let fieldRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var field: String
    public var value: String?
    public var exclude: Bool
    public var derivedFromProduct: Bool

    public init(field: String, value: String? = nil, exclude: Bool, derivedFromProduct: Bool) {
        self.field = field
        self.value = value
        self.exclude = exclude
        self.derivedFromProduct = derivedFromProduct
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case field
        case value
        case exclude
        case derivedFromProduct
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(field, forKey: .field)
        try container.encodeIfPresent(value, forKey: .value)
        try container.encode(exclude, forKey: .exclude)
        try container.encode(derivedFromProduct, forKey: .derivedFromProduct)
    }
}

