//
// FulfillmentInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Fulfillment information, such as the store IDs for in-store pickup or region IDs for different shipping methods. */
public struct FulfillmentInfo: Codable, JSONEncodable, Hashable {

    /** Fulfillment type. Place where product fulfilled. */
    public var type: String?
    /** Place ids where product fulfilled (array). */
    public var placeIds: [String]?

    public init(type: String? = nil, placeIds: [String]? = nil) {
        self.type = type
        self.placeIds = placeIds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case placeIds
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(placeIds, forKey: .placeIds)
    }
}

