//
// Image.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Product image */
public struct Image: Codable, JSONEncodable, Hashable {

    /** Absolute path to product image. */
    public var uri: String?
    /** Height in pixels */
    public var height: Int?
    /** Width in pixels */
    public var width: Int?

    public init(uri: String? = nil, height: Int? = nil, width: Int? = nil) {
        self.uri = uri
        self.height = height
        self.width = width
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case uri
        case height
        case width
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(uri, forKey: .uri)
        try container.encodeIfPresent(height, forKey: .height)
        try container.encodeIfPresent(width, forKey: .width)
    }
}

