//
// Merchandiser.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Merchandiser: Codable, JSONEncodable, Hashable {

    public var merchandiserId: String

    public init(merchandiserId: String) {
        self.merchandiserId = merchandiserId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case merchandiserId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(merchandiserId, forKey: .merchandiserId)
    }
}

