//
// NavigationType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Type of navigation. */
public enum NavigationType: String, Codable, CaseIterable {
    case value = "VALUE"
    case range = "RANGE"
}
