//
// NavigationTypeDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Type of navigation. */
public enum NavigationTypeDto: String, Codable, CaseIterable {
    case value = "Value"
    case range = "Range"
}
