//
// PriceInfoPriceEffectiveTime.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PriceInfoPriceEffectiveTime: Codable, JSONEncodable, Hashable {

    /** Timestamp seconds. */
    public var seconds: Int64?
    /** Timestamp nanos. */
    public var nanos: Int?

    public init(seconds: Int64? = nil, nanos: Int? = nil) {
        self.seconds = seconds
        self.nanos = nanos
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case seconds
        case nanos
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(seconds, forKey: .seconds)
        try container.encodeIfPresent(nanos, forKey: .nanos)
    }
}

