//
// ProductDtoColorInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProductDtoColorInfo: Codable, JSONEncodable, Hashable {

    /** Product color families (array). */
    public var colorFamilies: [String]?
    /** Product color (array). */
    public var colors: [String]?

    public init(colorFamilies: [String]? = nil, colors: [String]? = nil) {
        self.colorFamilies = colorFamilies
        self.colors = colors
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case colorFamilies
        case colors
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(colorFamilies, forKey: .colorFamilies)
        try container.encodeIfPresent(colors, forKey: .colors)
    }
}

