//
// Promotion.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The promotions applied to the product. A maximum of 10 values are allowed per product. */
public struct Promotion: Codable, JSONEncodable, Hashable {

    /** ID of the promotion. For example, 'free gift'. Length limit of 128 characters. */
    public var promotionId: String?

    public init(promotionId: String? = nil) {
        self.promotionId = promotionId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case promotionId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(promotionId, forKey: .promotionId)
    }
}

