//
// QueryPatternTriggerType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum QueryPatternTriggerType: String, Codable, CaseIterable {
    case contains = "CONTAINS"
    case endsWith = "ENDS_WITH"
    case regex = "REGEX"
    case startsWith = "STARTS_WITH"
    case matches = "MATCHES"
}
