//
// RecommendationsErrorResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Error returned by the API. */
public struct RecommendationsErrorResponse: Codable, JSONEncodable, Hashable {

    /** Identifier used for tracking purposes. */
    public var trackingId: String?
    /** HTTP method of the API call which produced the error. */
    public var method: String?
    /** HTTP path of the API call which produced the error. */
    public var path: String?
    /** Error message. */
    public var message: String?

    public init(trackingId: String? = nil, method: String? = nil, path: String? = nil, message: String? = nil) {
        self.trackingId = trackingId
        self.method = method
        self.path = path
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case trackingId
        case method
        case path
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(trackingId, forKey: .trackingId)
        try container.encodeIfPresent(method, forKey: .method)
        try container.encodeIfPresent(path, forKey: .path)
        try container.encodeIfPresent(message, forKey: .message)
    }
}

