//
// Refinement.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Refinement: Codable, JSONEncodable, Hashable {

    public var value: String
    public var priority: Int

    public init(value: String, priority: Int) {
        self.value = value
        self.priority = priority
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case value
        case priority
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(value, forKey: .value)
        try container.encode(priority, forKey: .priority)
    }
}

