//
// RuleTemplateSection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RuleTemplateSection: Codable, JSONEncodable, Hashable {

    public var zoneId: Int
    public var name: String
    public var zoneContent: String
    public var zoneType: ZoneType

    public init(zoneId: Int, name: String, zoneContent: String, zoneType: ZoneType) {
        self.zoneId = zoneId
        self.name = name
        self.zoneContent = zoneContent
        self.zoneType = zoneType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case zoneId
        case name
        case zoneContent
        case zoneType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(zoneId, forKey: .zoneId)
        try container.encode(name, forKey: .name)
        try container.encode(zoneContent, forKey: .zoneContent)
        try container.encode(zoneType, forKey: .zoneType)
    }
}

