//
// RuleType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum RuleType: String, Codable, CaseIterable {
    case regular = "REGULAR"
    case experiment = "EXPERIMENT"
}
