//
// SearchTerms.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Object with one single suggestion and associated info (brands and categories). */
public struct SearchTerms: Codable, JSONEncodable, Hashable {

    /** Suggestion itself. */
    public var value: String?
    public var additionalInfo: AdditionalInfo

    public init(value: String? = nil, additionalInfo: AdditionalInfo) {
        self.value = value
        self.additionalInfo = additionalInfo
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case value
        case additionalInfo
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(value, forKey: .value)
        try container.encode(additionalInfo, forKey: .additionalInfo)
    }
}

