//
// SearchMetadataDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Metadata relating to the search results, or how they were generated. */
public struct SearchMetadataDto: Codable, JSONEncodable, Hashable {

    /** Token to assist beacon collectors in correlating searches to user events. */
    public var searchAttributionToken: String?
    /** Were the search results from a previous call. */
    public var cached: Bool?
    /** Total time spent performing the Google search in milliseconds. */
    public var totalTime: Int64?

    public init(searchAttributionToken: String? = nil, cached: Bool? = nil, totalTime: Int64? = nil) {
        self.searchAttributionToken = searchAttributionToken
        self.cached = cached
        self.totalTime = totalTime
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case searchAttributionToken
        case cached
        case totalTime
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(searchAttributionToken, forKey: .searchAttributionToken)
        try container.encodeIfPresent(cached, forKey: .cached)
        try container.encodeIfPresent(totalTime, forKey: .totalTime)
    }
}

