//
// SearchResultsStats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SearchResultsStats: Codable, JSONEncodable, Hashable {

    /** Count of suggested sentences in response. */
    public var searchCount: Int?
    /** Time in milliseconds taken by autocomplete service to handle request and send response. */
    public var autocompleteResponse: Int64?
    /** Count of extended attributes in autocomplete response. */
    public var extendedAttributesCount: Int?
    /** Time in milliseconds taken by application to enrich response with extended attributes. */
    public var extendedAttributesResponse: Int64?

    public init(searchCount: Int? = nil, autocompleteResponse: Int64? = nil, extendedAttributesCount: Int? = nil, extendedAttributesResponse: Int64? = nil) {
        self.searchCount = searchCount
        self.autocompleteResponse = autocompleteResponse
        self.extendedAttributesCount = extendedAttributesCount
        self.extendedAttributesResponse = extendedAttributesResponse
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case searchCount
        case autocompleteResponse
        case extendedAttributesCount
        case extendedAttributesResponse
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(searchCount, forKey: .searchCount)
        try container.encodeIfPresent(autocompleteResponse, forKey: .autocompleteResponse)
        try container.encodeIfPresent(extendedAttributesCount, forKey: .extendedAttributesCount)
        try container.encodeIfPresent(extendedAttributesResponse, forKey: .extendedAttributesResponse)
    }
}

