//
// SelectedRefinementTriggerType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum SelectedRefinementTriggerType: String, Codable, CaseIterable {
    case range = "RANGE"
    case value = "VALUE"
    case navigationSelected = "NAVIGATION_SELECTED"
}
