//
// SelectedRefinementTrigger.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SelectedRefinementTrigger: Codable, JSONEncodable, Hashable {

    public var field: String
    public var value: String
    public var range: ModelRange
    public var type: SelectedRefinementTriggerType

    public init(field: String, value: String, range: ModelRange, type: SelectedRefinementTriggerType) {
        self.field = field
        self.value = value
        self.range = range
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case field
        case value
        case range
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(field, forKey: .field)
        try container.encode(value, forKey: .value)
        try container.encode(range, forKey: .range)
        try container.encode(type, forKey: .type)
    }
}

