//
// SortDtoOrderDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Order the products will appear in */
public enum SortDtoOrderDto: String, Codable, CaseIterable {
    case ascending = "Ascending"
    case descending = "Descending"
}
