//
// SpellCorrectionMode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum SpellCorrectionMode: String, Codable, CaseIterable {
    case auto = "AUTO"
    case suggestionOnly = "SUGGESTION_ONLY"
}
