//
// ValueFilterValueFilterType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ValueFilterValueFilterType: String, Codable, CaseIterable {
    case textual = "TEXTUAL"
    case numeric = "NUMERIC"
}
