//
// ZoneType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ZoneType: String, Codable, CaseIterable {
    case query = "QUERY"
    case content = "CONTENT"
    case richContent = "RICH_CONTENT"
    case expectQuery = "EXPECT_QUERY"
    case generatedContent = "GENERATED_CONTENT"
}
